import {StyleSheet, Dimensions} from 'react-native';
import commonStyle from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  containerSafee: {
    flex: 1,
    backgroundColor: '#fff',
    marginTop: 20,
  },
  containerStyle: {
    width: '100%',
    backgroundColor: '#fff',
    marginTop: windowHeight * 0.05,
  },
  spacerStyle: {},
  safeContainerStyle: {
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    // backgroundColor: 'tomato',
    marginBottom: windowHeight * 0.1,
  },
  ButtonContainer: {
    width: '80%',
    height: 50,
    borderRadius: 8,
    backgroundColor: 'rgba(173, 173, 173, 0.2)',
    marginTop: windowHeight * 0.015,
    alignSelf: 'center',
    marginBottom: 10,
    flexDirection: 'row',
  },
  ButtonText: {
    marginLeft: '5%',
    width: '78%',
    color: '#042C5C',
    fontSize: 15,
    marginTop: 17,
  },
  CountrySelect: {
    width: '80%',
    alignSelf: 'center',
    height: 48,
    borderColor: '#DADAED',
    borderWidth: 1,
    backgroundColor: '#fff',
    marginTop: 5,
    borderRadius: 7,
    flexDirection: 'row',
    marginBottom: 30,
  },
  InputNam: {
    marginLeft: '3%',
    fontSize: 15,
    fontFamily: commonStyle.regular,
    width: windowWidth * 0.65,
    // backgroundColor: 'gold',
    flex: 1,
    color: '#000',
  },
  ButtonStyle: {
    width: '80%',
    height: 45,
    borderRadius: 60,
    justifyContent: 'center',
    backgroundColor: '#3292E0',
    marginTop: 20,
    alignSelf: 'center',
    marginBottom: 70,
  },
  ButtonStyleText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 14,
    fontFamily: commonStyle.regular,
  },
  TotalContainer: {
    flexDirection: 'row',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
    // backgroundColor: 'tomato',
    marginBottom: windowHeight * 0.02,
  },
  TotalText: {
    width: '30%',
    fontSize: 18,
    fontFamily: commonStyle.regular,
    color: '#1C1939',
  },
  PriceText: {
    width: '68%',
    fontSize: 18,
    fontFamily: commonStyle.regular,
    textAlign: 'right',
    color: '#1C1939',
  },
  domicileStyle: {
    fontFamily: commonStyle.regular,
    fontSize: 18,
    textAlign: 'center',
    color: '#1C1939',
  },
  Heading: {
    fontSize: 18,
    fontFamily: commonStyle.Bold,
    textAlign: 'center',
    color: '#1C1939',
  },
  SecondHeading: {
    fontSize: 18,
    fontFamily: commonStyle.regular,
    textAlign: 'center',
    marginTop: 25,
    marginBottom: 15,
    color: '#1C1939',
  },
  inputCountryCustomContainer: {
    backgroundColor: '#fff',
    width: windowWidth * 0.8,
    height: 60,
    alignSelf: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#DADAED',
    borderRadius: 7,
  },
  phoneContainer: {
    // width: '75%',
    width: windowWidth * 0.7,
    height: 50,
    backgroundColor: '#fff',
    elevation: 0,
    // backgroundColor: 'tomato',
  },
  textInput: {
    paddingVertical: 0,
    // backgroundColor: 'gold',
    width: windowWidth * 0.6,
    backgroundColor: '#fff',
    fontFamily: commonStyle.regular,
    color: '#000',
  },
  codeTextStyle: {
    fontFamily: commonStyle.regular,
    fontSize: 15,
    // backgroundColor: 'green',
    width: 'auto',
  },
  countryPickerButtonStyle: {
    // backgroundColor: 'gold',
    width: 70,
  },
  textInputStyle: {
    fontFamily: commonStyle.regular,
    color: '#000',
  },
  dropContainerStyle: {
    justifyContent: 'center',
    // backgroundColor: 'tomato',
    width: windowWidth * 0.9,
    // borderRadius:0
    alignSelf: 'center',
    marginTop: windowHeight * 0.02,
    marginBottom: windowHeight * 0.01,
  },

  dropdown: {
    height: 50,
    borderRadius: 7,
    paddingHorizontal: 17,
    backgroundColor: 'rgba(173, 173, 173, 0.2)',
    // elevation: 1,
    width: windowWidth * 0.8,
    // borderWidth: 1,
    // borderColor: '#DADAED',
    alignSelf: 'center',
  },
  placeholderStyle: {
    fontSize: 16,
    fontFamily: commonStyle.regular,
    color: '#14213D',
  },
  selectedTextStyle: {
    fontSize: 16,
    fontFamily: commonStyle.regular,
    color: '#14213D',
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  containerrrrStyle: {
    marginTop: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 100,
    elevation: 10,
  },
});

export default styles;
