import {StyleSheet, Dimensions} from 'react-native';
import commonStyle from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  superCartContainer: {
    height: 'auto',
    width: windowWidth * 0.95,
    backgroundColor: '#F4F6F8',
    borderRadius: 30,
    elevation: 1,
    marginTop: windowHeight * 0.03,
  },
  firstContainer: {
    backgroundColor: '#F4F6F8',
    alignSelf: 'center',
    height: windowHeight * 0.3,
    width: windowWidth * 0.95,
    borderTopLeftRadius: 30,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: windowHeight * 0.03,
  },
  secondContainer: {
    backgroundColor: '#F4F6F8',
    alignSelf: 'center',
    height: windowHeight * 0.08,
    width: windowWidth * 0.95,
    borderRadius: 30,
    // borderBottomRightRadius: 30,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: windowHeight * 0.015,
    flexDirection: 'row',
  },
  firstRow: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
  },
  secondRow: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
  },
  thirdRow: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
  },
  coounterContainer: {
    // backgroundColor: 'gold',
    flexDirection: 'row',
    height: windowHeight * 0.1,
    width: windowWidth * 0.3,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  WeightCalText: {
    color: '#000',
    fontSize: 18,
    fontFamily: commonStyle.Bold,
  },
  WeightCalSubText: {
    color: '#3F4C58',
    fontSize: 16,
    fontFamily: commonStyle.regular,
  },
  counterTExt: {
    fontSize: 26,
    color: 'gray',
  },
  counterButton: {
    width: 40,
    height: 40,
    borderRadius: 100,
    backgroundColor: '#DFE8F2',
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterButtonText: {
    color: '#A1B0C1',
    fontSize: 20,
  },
  cartIcon: {
    // backgroundColor: 'green',
    width: windowWidth * 0.06,
    height: 25,
  },
  cartText: {
    color: 'gray',
    fontSize: 14,
    fontFamily: commonStyle.Bold,
    fontWeight:'650',
    // backgroundColor: 'tomato',
    marginLeft: 10,
    width: windowWidth * 0.4,
  },
  cartshshText: {
    color: '#000',
    textAlign: 'center',
    fontSize: 12,
    fontFamily: commonStyle.regular,
  },
  cartsubText: {
    color: '#8998A8',
    fontSize: 14,
    fontFamily: commonStyle.regular,
    textAlign: 'center',
  },
  cartContaineer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.25,
    height: windowHeight * 0.05,
  },
  buttonContaineer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: windowWidth * 0.5,
    height: windowHeight * 0.05,
    backgroundColor: '#fff',
    borderRadius: 10,
    elevation: 1,
  },
  discountCodeInputStyle: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.35,
    height: 'auto',
    fontFamily: commonStyle.regular,
    color: '#000',
    textAlignVertical: 'center',
    fontSize: 12,
  },
  priceText: {
    fontFamily: commonStyle.Bold,
    fontSize: 12,
    color: '#000',
  },
  totalContainer: {
    // backgroundColor: 'green',
    alignSelf: 'center',
    // height: windowHeight * 0.08,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: windowHeight * 0.01,
    flexDirection: 'row',
  },
  totalText: {
    fontSize: 17,
    fontFamily: commonStyle.Bold,
    color: '#3F4C58',
    // backgroundColor: 'tomato',
  },
  btnContainer: {
    backgroundColor: '#3292E0',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowHeight * 0.01,
    width: windowWidth * 0.8,
    height: windowHeight * 0.07,
    borderRadius: 40,
    marginBottom: 20,
  },
  btnText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: commonStyle.regular,
  },
  ButtonContainer: {
    width: 250,
    height: 45,
    borderRadius: 60,
    justifyContent: 'center',
    backgroundColor: '#3292E0',
    marginTop: '25%',
    alignSelf: 'center',
    marginBottom: 10,
  },
  ButtonText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 14,
    fontFamily: commonStyle.regular,
  },
  btnClearBasket:{
    marginTop:15,
    marginLeft:'70%'
  },
  btnClearBasketText:{
    textAlign:'left',
    color: '#3292E0',
    fontSize: 14,
    fontFamily: commonStyle.Bold,
  },
});

export default styles;
