export default {
  SplashScreen: 'Splash Screen',
  Login: 'Login',
  Signup: 'Signup',
  Optcode: 'Optcode',
  SelectService: 'SelectService',
  CountryDelivery: 'CountryDelivery',
  ReturnByService: 'ReturnByService',
  PaymentMethods: 'PaymentMethods',
  OrderedRegistered: 'OrderedRegistered',
  Research: 'Research',
  WeightCal: 'WeightCal',
  OrderValidated: 'OrderValidated',
  SuccessFullyRegOrder: 'SuccessFullyRegOrder',
  PaymentDetails: 'PaymentDetails',
  AppSettingsMain: 'AppSettingsMain',
  OrderDetails: 'OrderDetails',
  Address: 'Address',
  CreditCard: 'CreditCard',
  ContactUs: 'ContactUs',
  ServiceClientContact: 'ServiceClientContact',
  PickupWindow: 'PickupWindow',
  DeliveryMethodsU: 'DeliveryMethodsU',
  Language: 'Language',
  Discount: 'Discount',
  Profile: 'Profile',
  ConfirmSent: 'ConfirmSent',
  TermsOfUse: 'TermsOfUse',
  LegalNotice: 'LegalNotice',
  TermsAndConditions: 'TermsAndConditions',
};
